project:
  type: website

website:
  title: "programming historian"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tuto.ipynb
        text: Notebook
      - href: tramme-generale.qmd
        text: Tramme générale
      - href: tuto.qmd
        text: Tuto rédigé


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
