# Sommaire

- Intro
    - Situer la famille du topic modelling (histoire, application recherche) et comparer BERTopic / LDA
    - Brève histoire de Bertopic
- Understand the ins and outs
    - Out-of the box; schema what to expect
    - Understand each step
- Use case 
    - Introduction au jeu de données (oublie le prétraitement) 
    - Show case des résultats
    - Pipeline de fit -> toucher sur les principaux paramètres et comment les choisir
    - Présentation des résultats (lire les graphes) 
    - Sauvegarder les données + stats descriptive
- Conclusion 
    - Ouverture sur question de l’évaluation
    - Ouverture sur la gestion plus fine des groupes (merge)
    - Ouverture sur la reproductibilité
    - Renvoyer vers le tutoriel complet

# Proposition de leçon pour Programming Historian (édition française)


Nom : Axel Morin (auteur principal)
Adresse mail : axel.morin@ensae.fr


Nom : Émilien Schultz
Adresse mail : emilien.schultz@ensae.fr

Quel type de proposition souhaitez-vous faire ? 

- [x] Une leçon originale en français *Répondez aux questions de la section 2*
- [ ] Une traduction en français d'une leçon originale en anglais, espagnol ou portugais *Répondez aux questions de la section 3*


### Section 2 : Leçons originales en français

Répondez aux question suivantes si vous proposez une leçon *originale* en français. 

a). Quel est le titre de votre leçon ? 

> Explorer et classifier les thèmes d'un corpus de textes avec BERTopic et Python

1. Qu'est-ce que les lecteurs et lectrices apprendront dans votre leçon ?
[3-4 phrases]

> La leçon a deux objectifs principaux : le premier est d'introduire les concepts de topic modelling et de regroupement de textes en présentant les grandes familles de stratégies existantes ; le second est de montrer comment utiliser la bibliothèque BERTopic en Python pour réaliser une classification des textes en utilisant le topic modelling. Cela sera l'occasion de souligner les bonnes pratiques et les paramètres importants pour favoriser la reproductibilité, et de discuter l'usage des modèles de langages.
 
> À la fin de la leçon, les lecteur.ice.s pourront identifier les cas dans lesquels une analyse de thème avec bertopic est pertinent et initier sa mise en oeuvre.

> À savoir, la leçon proposée serait une version condensée du tutoriel [The General Inquirer in the time of LLMs: a BERTopic tutorial](https://css-polytechnique.github.io/css-ipp-materials/pages/bertopic-tutorial.html) dont nous sommes les auteurs. 


> Programming historian a déjà publié plusieurs leçons autour des concepts et méthodes de traitement de données textuelles[^ref-PH-NLP]. Plus particulièrement, de nombreuses leçons présentent des méthodes pour explorer un corpus de texte par des techniques de _lecture distante_ ([Corpus Analysis with Antconc](https://programminghistorian.org/en/lessons/corpus-analysis-with-antconc); [Scalable Reading of Structured Data](https://programminghistorian.org/en/lessons/scalable-reading-of-structured-data)) ou bien des techniques de topic modelling ([Getting Started with Topic Modeling and MALLET](https://programminghistorian.org/en/lessons/topic-modeling-and-mallet)).

> Cette leçon permet de compléter les différentes méthodes en se concentrant sur une bibliothèque récente et beaucoup utilisée qui mobilise les modèles de langage pour produire des regroupement sur la base du sens des textes. La majorité des leçons sur le NLP sont pour le moment en anglais et non traduite, cette leçon permettra donc de renforcer les lectures pour PH francophone. Notre leçon prolongerait les leçons déjà existantes ([Clustering with Scikit-Learn in Python](https://programminghistorian.org/en/lessons/clustering-with-scikit-learn-in-python); [Understanding and Creating Word Embeddings](https://programminghistorian.org/en/lessons/understanding-creating-word-embeddings); [Corpus Analysis with Voyant Tools](https://programminghistorian.org/en/lessons/corpus-analysis-voyant-tools); [Getting Started with Topic Modeling and MALLET](https://programminghistorian.org/en/lessons/topic-modeling-and-mallet)) et permettrait d'en étendre le champs ([Clustering and Visualising Documents using Word Embeddings](https://programminghistorian.org/en/lessons/clustering-visualizing-word-embeddings)); le tout proposé à un public francophone

[^ref-PH-NLP]: [Analyse de documents avec TF-IDF](https://programminghistorian.org/fr/lecons/analyse-de-documents-avec-tfidf); [Introduction to stylometry with Python](https://programminghistorian.org/en/lessons/introduction-to-stylometry-with-python); [Understanding and Using Common Similarity Measures for Text Analysis](https://programminghistorian.org/en/lessons/common-similarity-measures); [Corpus Analysis with spaCy](https://programminghistorian.org/en/lessons/corpus-analysis-with-spacy)

[^precision-word-embedding]: Le plus souvent, on présente des représentations dites creuses (TF-IDF) ou bien des représentation dense mais sans prise en compte du contexte (Word2Vec).

3. Veuillez expliquer comment vous en êtes venu·e à utiliser cette méthode ou cet outil dans le cadre de votre travail dans le domaine des sciences humaines et sociales. 
[100-300 mots]

> Nous sommes venus à utiliser BERTopic au sein de l'équipe dans différents projets et avons vu son usage augmenter dans notre domaine (sciences sociales computationnelles). Cet outil est particulièrement utile d'une part pour faire de l'exploration sur de grands corpus, et d'autre part pour entrer dans une démarche pédagogique sur les approches de NLP basées sur les plongements de phrases. Nous avons aussi constaté l'existence d'une littérature qui commence à comparer cette méthode à d'autres plus anciennes, et donc nous trouvons intéressant d'avoir une leçon sur le sujet.


4. Parlez-nous de l'étude de cas que vous proposez d'utiliser dans votre leçon. Les meilleures leçons s'appuient sur des jeux de données authentiques ainsi que sur des exemples de code que les lecteurs et lectrices peuvent manipuler.
[100-300 mots]

> Dans le cadre de cette leçon, nous utilisons le corpus des résumés de thèses défendues en France entre 2010 et 2022 disponible sur data.gouv.fr et filtré. Ce jeu de donné est très large, et donc justifie l'emploi de ces techniques; par ailleurs il est souvent convoqué dans des travaux de sciences sociales (par exemple, La part du genre, Boaelaert et al., 2025). Le jeu de données nettoyé est d'ailleurs déposé sur Zenodo pour faciliter la reproductibilié.

5. Expliquez en quoi votre choix de logiciels et de données soutiendra notre engagement pour la science ouverte. Nous préconisons l'utilisation de logiciels libres, de langages de programmation libres et d'ensembles de données libres d'accès dans la mesure du possible. Utilisez les questions suivantes pour structurer votre réponse :
- Quels sont les logiciels libres, les outils libres, les langages de programmation libres ou les ensembles de données libres utilisés dans cette leçon ?
- Quels sont les logiciels propriétaires ou les outils commerciaux (s'il y en a) utilisés dans cette leçon ? Nous vous recommandons vivement d'opter pour des alternatives open source.
- Quels sont (le cas échéant) les coûts et conditions nécessaires à l'utilisation de cette méthode ou de cet outil ? Précisez notamment s'il faut s'inscrire ou fournir des informations bancaires.
[100-300 mots]

> La leçon utilise le language de programmation Python ainsi que des librairies libres utilisable par toustes. Le jeu de données est lui aussi en libre accès sur le site [data.gouv.fr](https://www.data.gouv.fr/datasets/theses-soutenues-en-france-depuis-1985).

> Il est important de noter cependant que le calcul d'embeddings nécessite une puissance de calcul non négligeable et peut donc nécessiter des ressources matérielles. Pour faciliter l'utilisation des outils dans le cadre de cette leçon, nous avons rendu disponible plusieurs jeux d'embeddings sur [Zenodo](https://zenodo.org/records/17936091).

6. Dites-nous si la méthode ou l'outil dont parle votre leçon est adapté à des utilisations avec d'autres langues que le français. (Nous privilégions les méthodologies et outils qui peuvent être utilisés dans des contextes multilingues, mais ce n'est pas une obligation). 
[100-300 words]

> Cet outil est complètement agnostique de la langue. La plupart des ressources disponibles sur cet outil sont en anglais, et elles sont toutes adaptables à d'autres langues en utilisant le bon modèle de plongement. C'est d'ailleurs l'intérêt d'une leçon en français qui permettra de compléter la documentation uniquement en anglais.

7. Please outline any technical prerequisites and potential limitations of access to using this method or tool:
- Our readers work with different operating systems and have varying computational resources.  
[100-200 words]

> Comme dit précédemment, le calcul de plongements peut être difficile et long en fonction du matériel informatique. Pour y faire face, nous proposons plusieurs jeux d'embeddings disponibles sur [Zenodo](https://zenodo.org/records/17936091). 

Veuillez décrire les prérequis techniques et les potentielles difficultés d'accès à l'utilisation de la méthode ou de l'outil décrit dans la leçon. 
- Notre lectorat international utilise des systèmes d'exploitation différents et dispose de ressources informatiques variées.
[100-200 mots]

> - Maîtrise intermédiaire de Python et des environnements virtuels
> - Maitrise de base des notions de machine learning (réduction de dimensionnalité et clustering)
> - Maîtrise de base des notions de NLP (notion de tokenisation, de tf-idf).

8. Lien optionnel vers un exemple de code ou un extrait de la leçon proposée sur votre dépôt GitHub personnel :

[The General Inquirer in the time of LLMs: a BERTopic tutorial](https://css-polytechnique.github.io/css-ipp-materials/pages/bertopic-tutorial.html)